FROM quay.io/astronomer/astro-runtime:12.7.1
COPY settings.py /usr/local/lib/python3.12/site-packages/settings.py
COPY utils.py /usr/local/lib/python3.12/site-packages/utils.py
RUN pip install --upgrade pip